name: TikTok Auto Upload
on:
  schedule:
    - cron: "0 12 * * *"  # Daily at 12 PM UTC (5 AM PST)
    
jobs:
  generate-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TIKTOK_SESSION: ${{ secrets.TIKTOK_SESSION }}
        run: python main.py
